// Automatically generated by make_root_pointers.py.

const char *readline_hist[(8)];
mp_obj_list_t mp_sys_argv_obj;
mp_obj_list_t mp_sys_path_obj;
mp_obj_t dupterm_objs[(3)];
mp_obj_t track_reloc_code_list;
mp_sched_item_t sched_queue[(8)];
struct _machine_i2s_obj_t *machine_i2s_obj[(2)];
struct _machine_timer_obj_t *timer_table[3];
struct _mp_vfs_mount_t *vfs_cur;
struct _mp_vfs_mount_t *vfs_mount_table;
void *machine_pin_irq_objects[(4 * 32 + 3)];
