/* #undef SDL2COMPAT_VENDOR_INFO */
#define SDL_REVISION_NUMBER 0

#ifdef SDL2COMPAT_VENDOR_INFO
#define SDL_REVISION "SDL-2.90.0-gc5fae2fd2 (" SDL2COMPAT_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.90.0-gc5fae2fd2"
#endif
